### ISSUE TITLE
How to obtain a list of all assigned unicode?

### ISSUE THREAD

**Issue by vic0707** [node-unicode/unicode-10.0.0#1]
Hi,

Great package. I am trying to obtain a list of all assigned named characters. They should be 136,690 if my research is correct. How could I find this in this package?

**Comment by mathiasbynens** [comment]
Try searching the `README` for `Assigned` ;)

```js
require('unicode-10.0.0/Binary_Property/Assigned/code-points.js');
require('unicode-10.0.0/Binary_Property/Assigned/symbols.js');
require('unicode-10.0.0/Binary_Property/Assigned/regex.js');
```
